### ISSUE TITLE
Consider deprecating in favour of official action

### ISSUE THREAD

**Issue by G-Rath** [kopepasah/setup-pantheon-terminus#14]
Terminus now have an official GitHub Action which is composite based and has a few more features: https://github.com/pantheon-systems/terminus-github-actions

It's probably worth deprecating this action to avoid confusion since it does the same thing.

**Comment by kopepasah** [comment]
Ooh, shiny. I didn't even notice. 👏 

Yeah, that makes sense. Let me put together a plan.

**Comment by kopepasah** [comment]
This Action has been deprecated. Please now use the [official Pantheon Systems Action for installing and using Terminus](https://github.com/pantheon-systems/terminus-github-actions).
