### ISSUE TITLE
ubuntu-latest now uses PHP 7.4

### ISSUE THREAD

**Issue by nichol-fluke** [kopepasah/setup-pantheon-terminus#4]
Hello! On 12/22/20, when this action began installing terminus, I started seeing `Error: The process 'sudo' failed with exit code 1` . I had not seen this previously. I found that the update on ubuntu-latest (18.04 to 20.04) now uses PHP 7.4 and 8.0: 
https://github.com/actions/virtual-environments/issues/1816
In my own repo's yaml file, from your workflow example, I have changed the PHP version and it seems to work, I no longer get the error. 
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        **php-version: '7.4'**

**Comment by TheLastCicada** [comment]
Same issue for me - haven't tried the workaround specifying the PHP version, but this is broken without it.

**Comment by TheLastCicada** [comment]
Confirmed the solution presented by @nichol-fluke works.  Before I didn't need to install PHP separately for Terminus to install successfully, but now this is necessary to have the Terminus install work.  Rather than `ubuntu-latest` I switched to `ubuntu-18.04` and still have the problem without installing PHP specifically in my job.

**Comment by nichol-fluke** [comment]
Seconding @TheLastCicada 's comment -
Before I did not have to install PHP. 
When I tried using `ubuntu-18.04` and leaving out the PHP version it still did not work as it used to.

**Comment by kopepasah** [comment]
Thanks for reporting. I will not be able to look at this for at least a couple weeks, but happy to review and PRs that address this issue.

**Comment by seanr** [comment]
Any updates? I just ran into this trying to set up a new GitHub Action. I _think_ for now I can get away with skipping the Terminus stuff, but it would be nice to have resolution on this.

**Comment by G-Rath** [comment]
@seanr I've not hit this issue myself, but we created a [new action](https://github.com/ackama/setup-terminus) for setting up Terminus for other reasons, that you could try - it hopefully shouldn't have this issue, but if it does you can open an issue and we'll look into it :)

**Comment by kopepasah** [comment]
This Action has been deprecated. Please now use the [official Pantheon Systems Action for installing and using Terminus](https://github.com/pantheon-systems/terminus-github-actions).
