### ISSUE TITLE
Composer is old version - fails at semver

### ISSUE THREAD

**Issue by bob-hinrichs** [kopepasah/setup-pantheon-terminus#5]
As I am looking into this, I think this is a duplicate issue, sorry if so.  That wasn't apparent at first.  It is trying to build our composer and getting conflicts.  Will look at the other issue.

You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2</warning>
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: composer/semver[3.2.2, 1.x-dev].
    - Can only install one of: composer/semver[1.x-dev, 3.2.2].
    - pantheon-systems/terminus 2.5.0 requires composer/semver ^1.4 -> satisfiable by composer/semver[1.x-dev].
    - Installation request for pantheon-systems/terminus ^2.5 -> satisfiable by pantheon-systems/terminus[2.5.0].
    - Installation request for composer/semver (locked at 3.2.2, required as ^3) -> satisfiable by composer/semver[3.2.2].

**Comment by kopepasah** [comment]
Thanks for the report, @bob-hinrichs. Going to slot some time to revisit this project next week.

**Comment by dschmidtadv** [comment]
I got the same problem!
```
  Problem 1
    - Installation request for pantheon-systems/terminus ^2.5 -> satisfiable by pantheon-systems/terminus[2.5.0].
    - Conclusion: don't install composer/semver 3.2.2
    - pantheon-systems/terminus 2.5.0 requires composer/semver ^1.4 -> satisfiable by composer/semver[1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.x-dev].
    - Can only install one of: composer/semver[1.4.0, 3.2.2].
    - Can only install one of: composer/semver[1.4.1, 3.2.2].
    - Can only install one of: composer/semver[1.4.2, 3.2.2].
    - Can only install one of: composer/semver[1.5.0, 3.2.2].
    - Can only install one of: composer/semver[1.5.1, 3.2.2].
    - Can only install one of: composer/semver[1.5.2, 3.2.2].
    - Can only install one of: composer/semver[1.6.0, 3.2.2].
    - Can only install one of: composer/semver[1.7.0, 3.2.2].
    - Can only install one of: composer/semver[1.7.1, 3.2.2].
    - Can only install one of: composer/semver[1.7.2, 3.2.2].
    - Can only install one of: composer/semver[1.x-dev, 3.2.2].
    - Installation request for composer/semver (locked at 3.2.2) -> satisfiable by composer/semver[3.2.2].

```

**Comment by dschmidtadv** [comment]
@kopepasah  Are you still  planning to look into that? It's the one missing pieces for my Github/PAntheon workflow. Happy to help with testing if I can!

**Comment by kopepasah** [comment]
@dschmidtadv my time is very limited, but we are open to PRs. 

However, I will note that there is a new Pantheon project coming up and it will require me to modernize and fix this issue, as the project is using Composer 2.0.

**Comment by kopepasah** [comment]
This Action has been deprecated. Please now use the [official Pantheon Systems Action for installing and using Terminus](https://github.com/pantheon-systems/terminus-github-actions).
