### ISSUE TITLE
Feature request: Install specific version of terminus via environment variable or flag?

### ISSUE THREAD

**Issue by apotek** [kopepasah/setup-pantheon-terminus#7]
Recent updates to terminus have wreaked havoc on some workflows. When working manually, we are reverting to version 2.6.1 of terminus. However, for workflows, we are using this great action and we see that the action uses terminus at wherever master points to.

I am wondering if we could set an environment variable (say TERMINUS_VERSION) and when using this action, the action could sniff for that environment variable and either install the version requested or default to master as it does.

```sh
await exec.exec( 'sudo php installer.phar install' ); // Sudo is required in order to install bin/terminus.
```

instead:
```sh
await exec.exec( 'sudo php installer.phar install --install-version ${TERMINUS_VERSION}' ); // Sudo is required in order to install bin/terminus.
```

**Comment by kopepasah** [comment]
This Action has been deprecated. Please now use the [official Pantheon Systems Action for installing and using Terminus](https://github.com/pantheon-systems/terminus-github-actions).
