### ISSUE TITLE
Many forks

### ISSUE THREAD

**Issue by bob-hinrichs** [kopepasah/setup-pantheon-terminus#8]
It seems like 2 years ago, many folks needed to fork this in order to get it working.  There are issues in here with promises of updating the package, but I guess there was no time to do it. Is this project dead?  Is there a better package to use for terminus via github actions?  Oddly, it appears Pantheon has nothing to say about it.  

My own sad story...  the fork I was using (the one most recently changed, from achieve media/gclicon) stopped working suddenly without any changes on our end.  Pantheon cannot help me, they are asking for a stack trace that is not provided.  It logs in via terminus successfully then mysteriously fails the terminus command with "too many attempts." I've replaced the ssh key and token, same issue.  I don't expect someone to tell me the solution, but I am feeling like this is a dead end so thought I would ask about it.

**Comment by kopepasah** [comment]
This Action has been deprecated. Please now use the [official Pantheon Systems Action for installing and using Terminus](https://github.com/pantheon-systems/terminus-github-actions).
